name: Deploy to EKS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy to EKS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Install Helm
              uses: azure/setup-helm@v3

            - name: Update kubeconfig
              run: |
                  aws eks update-kubeconfig --name eks-cluster

                  - name: Deploy to EKS
                  run: |
                    kubectl config set-context --current --namespace=default
                    helm upgrade --install botgauge-chart-release./helm-chart \
                      --set image.repository=yoismak/hellobotgauge \
                      --set image.tag=${GITHUB_SHA::7} \
                      --namespace default
                  env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}
